### ISSUE TITLE
Supposed use?

### ISSUE THREAD

**Issue by VelocityRa** [nicolasartman/town-of-salem-tool#3] opened 2015-10-08 17:24 UTC
I'm not sure if there's a problem with the tool, I got it to work (by adding `javascript:` before the bookmarklet code), but I don't understand how to use it.
When I click it, it opens up a transparent interface that I can resize and move around, but where _am_ I supposed to put it?
The entire screen doesn't make sense, is it the Graveyard/Rolelist? What does the middle column do, if so?

**Comment by nicolasartman** [comment] 2015-10-11 09:34
duplicate of #2

**Closed as completed by nicolasartman** 2015-10-11 09:34 UTC
